"""initial schema - owners, vehicles, audit_log

Revision ID: 4d0b280b6133
Revises: 
Create Date: 2026-05-09 20:12:42.956849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '4d0b280b6133'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_log')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('request_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('service', sa.VARCHAR(length=50), nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), nullable=False),
    sa.Column('table_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('record_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('old_data', sqlite.JSON(), nullable=True),
    sa.Column('new_data', sqlite.JSON(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
